### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by luv2dnce33** [szTheory/programmingnewsletters.com#1]
https://hackernewsletter.com/

https://securib.ee/newsletter/

https://newsletter.intigriti.com/

**Comment by luv2dnce33** [comment]
Thanks for the quick deploy! Love the site. Maybe @securibee can advise more on if there is a way to index the HiveFive newsletter they publish.

**Comment by luv2dnce33** [comment]
This is another pretty good one: https://bluepurple.substack.com/

**Comment by szTheory** [comment]
Added, thanks!

**Comment by luv2dnce33** [comment]
Can we add: https://blog.intigriti.com/category/bugbytes/

and the /weekly/ round up of https://hackernewsletter.com/ ?
